# Generated by Django 5.0.7 on 2024-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addfaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('facultyname', models.CharField(max_length=50)),
                ('facultyemail', models.CharField(max_length=50)),
                ('facultypassword', models.CharField(max_length=50)),
            ],
        ),
    ]
