# Generated by Django 5.1.1 on 2024-09-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ackdate', models.CharField(max_length=50)),
                ('ackdesignation', models.CharField(max_length=50)),
                ('ackname', models.CharField(max_length=50)),
                ('ackemail', models.CharField(max_length=50)),
                ('ackmsg', models.CharField(max_length=50)),
            ],
        ),
    ]
