# Generated by Django 5.0.7 on 2024-09-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('complaintto', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('complaintmsg', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='complaintregister',
        ),
    ]
