# Generated by Django 5.0.7 on 2024-09-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_complaintdetails_delete_complaintregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetails',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
