# Generated by Django 5.1.1 on 2024-10-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_complaintdetailss_delete_complaintdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetailss',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
